export const BASE_URI: string =
  "https://pub-5c15a84b97fc4cc889a06969fb95be5f.r2.dev";
export const partners: partners[] = [
  {
    id: 1,
    logo: BASE_URI + "/home/partners/1/logo.png",
    name: "The Conference of the Parties 29",
    link: "https://cop29.az/en",
    animated: true,
    color: "#006a72",
  },
  {
    id: 2,
    logo: BASE_URI + "/home/partners/2/logo.png",
    name: "Lightsource BP",
    link: "https://lightsourcebp.com/",
    color: "#009900",
  },
  {
    id: 3,
    logo: BASE_URI + "/home/partners/3/logo.png",
    name: "ILF Consulting Engineers",
    link: "https://www.ilf.com/",
    color: "#2f5291",
  },
  {
    id: 4,
    logo: BASE_URI + "/home/partners/4/logo.png",
    name: "Suez SA",
    link: "https://www.suez.com/en",
    color: "#7ecb23",
  },
  {
    id: 5,
    logo: BASE_URI + "/home/partners/5/logo.png",
    name: "PMD Projects LLC",
    link: "https://pmdprojects.az/",
    color: "#015ba9",
  },
  {
    id: 6,
    logo: BASE_URI + "/home/partners/6/logo.png",
    name: "Dashkasan Iron Ore LLC",
    link: "https://ddf.az",
    color: "#7c5541",
  },
  {
    id: 7,
    name: "BALKHOORMA LLC",
    logo: BASE_URI + "/home/partners/7/logo.png",
    link: "https://balkhoorma.com/en",
    color: "#558551",
    animated: true,
    projects: [
      {
        name: "BALKHOORMA LLC Natural Food Collection",
        heading: "Cənubi Qafqazda ilk meyvə-qurtma zavodu (Xurma)",
        desc: "Balakən rayonu, Katex k. ərazisində 2.0 ha ərazidə yerləşən 1 ədəd 2 mərtəbəli ofis binası, 2 ədəd saoyuducu binası, 1 ədəd istehsalat binası, 10 nəfərlik qonaq evi və köməkçi binaları",
        images: [
          BASE_URI + "/home/partners/7/1.jpeg",
          BASE_URI + "/home/partners/7/2.jpeg",
        ],
      },
      {
        name: "BALKHOORMA-PİRKEKE LLC",
        heading: "Ağdaş rayonunda 16 000.0 m2 meyve-qurutma zavodu",
        desc: "Ağdaş rayonu,Pirkəkə k. ərazisində yerləşən 10.0ha ərazidə 5ədəd meyvə-qurutma anbarı,1ədəd ofis binası,2 ədəd məhsul qəbul edici anbar binası və köməkçi binaları",
        images: [
          BASE_URI + "/home/partners/7/3.jpeg",
          BASE_URI + "/home/partners/7/4.jpeg",
        ],
      },
    ],
  },
  {
    id: 8,
    logo: BASE_URI + "/home/partners/8/logo.png",
    name: "Encotec Company",
    color: "#01205a",
    link: "https://www.encotec.az/",
  },
  {
    id: 9,
    logo: BASE_URI + "/home/partners/9/logo.png",
    name: "AzerBlast LLC",
    link: "https://azerblast.az/",
    color: "#e96453",
  },
  {
    id: 10,
    logo: BASE_URI + "/home/partners/10/logo.png",
    name: "Ministry of Ecology and Natural Resources",
    link: "https://eco.gov.az/",
    animated: true,
    color: "#fef212",
  },
  {
    id: 11,
    logo: BASE_URI + "/home/partners/11/logo.png",
    name: "Ministry of Economy of Azerbaijan Republic",
    link: "https://www.economy.gov.az/en",
    animated: true,
    color: "#a2925e",
  },
  {
    id: 12,
    logo: BASE_URI + "/home/partners/12/logo.png",
    name: "Azerbaijan Amelioration and Water Farm OJSC",
    link: "https://mst.gov.az/en",
    animated: true,
    color: "#0191cf",
  },
  {
    id: 13,
    logo: BASE_URI + "/home/partners/13/logo.png",
    name: "Restoration, Construction, and Management Service in the Karabakh Economic Region",
    animated: true,
    link: "https://rebuildkarabakh.az",
    color: "#000000",
  },
  {
    id: 14,
    name: "Technol LLC",
    logo: BASE_URI + "/home/partners/14/logo.png",
    link: "https://technol.az/en/",
    color: "#c82327",
    projects: [
      {
        name: "Technol LLC",
        heading: "Cənubi Qafqazda ilk maşın-motor emalı yağları zavodu",
        desc: "Sumqayıt şəhərində, 1.5 ha ərazidə yerləşən, 1 ədəd 2 mərtəbəli ofis binası, 1 ədəd istehsalat binası və 2 ədəd məhsul saxlama anbarı",
        images: [
          BASE_URI + "/home/partners/14/1.jpeg",
          BASE_URI + "/home/partners/14/2.jpeg",
          BASE_URI + "/home/partners/14/3.jpeg",
          BASE_URI + "/home/partners/14/4.jpeg",
          BASE_URI + "/home/partners/14/5.jpeg",
        ],
      },
    ],
  },
  {
    id: 15,
    logo: BASE_URI + "/home/partners/15/logo.png",
    name: "Sobsan Paints",
    color: "#e12917",
    link: "https://sobsan.com/",
  },
  {
    id: 16,
    logo: BASE_URI + "/home/partners/16/logo.png",
    name: "ACWA Power",
    link: "https://www.acwapower.com/en/",
    color: "#bb332f",
  },
  {
    id: 17,
    logo: BASE_URI + "/home/partners/17/logo.png",
    name: "Tractabel",
    link: "https://tractebel-engie.com/en",
    color: "#09aafe",
  },
  {
    id: 18,
    logo: BASE_URI + "/home/partners/18/logo.png",
    name: "SOCAR Midstream Operations",
    link: "https://www.socarmidstream.az/",
    color: "#e4002b",
  },
  {
    id: 19,
    logo: BASE_URI + "/home/partners/19/logo.png",
    name: "Suraxanı Oil",
    link: "https://www.surakhani-oil.com/",
    color: "#f16333",
  },
  {
    id: 20,
    logo: BASE_URI + "/home/partners/20/logo.png",
    name: "Power Construction Corporation of China",
    color: "#c80b4b",
    link: "https://en.powerchina.cn/",
    animated: true,
  },
  {
    id: 21,
    logo: BASE_URI + "/home/partners/21/logo.png",
    name: "MAQRO Group",
    link: "https://www.maqro.ge/",
    color: "#42a13e",
  },
  {
    id: 22,
    logo: BASE_URI + "/home/partners/22/logo.png",
    name: "Referans Clinical Laboratory and Polyclinic Center",
    color: "#0aa4c7",
    link: "https://referansclc.com/",
    animated: true,
  },
  {
    id: 23,
    logo: BASE_URI + "/home/partners/23/logo.png",
    name: "Food Safety Agency of the Republic of Azerbaijan",
    link: "https://afsa.gov.az/",
    animated: true,
    color: "#d9a183",
  },
  {
    id: 24,
    logo: BASE_URI + "/home/partners/24/logo.png",
    name: "Azerbaijan Airlines",
    link: "https://azal.az/en/",
    color: "#56bfe7",
  },
  {
    id: 25,
    logo: BASE_URI + "/home/partners/25/logo.png",
    name: "YPT Yılmaz Proses Teknolojileri",
    link: "https://www.ypt.com.tr/",
    color: "#fbb900",
  },
  {
    id: 26,
    logo: BASE_URI + "/home/partners/26/logo.png",
    name: "CQA International LTD",
    color: "#7aa02f",
    link: "https://www.cqainternational.co.uk/",
  },
  {
    id: 27,
    logo: BASE_URI + "/home/partners/27/logo.png",
    name: "Bravo Supermarket Chain",
    link: "https://www.bravosupermarket.az/",
    color: "#77bc1f",
  },
  {
    id: 28,
    logo: BASE_URI + "/home/partners/28/logo.png",
    name: "Azerbaijan Company for Poultry Development",
    color: "#00495b",
    link: "https://az.linkedin.com/company/azerbaijan-company-for-poultry-development",
    animated: true,
  },
  {
    id: 29,
    logo: BASE_URI + "/home/partners/29/logo.png",
    name: "AzerGold CJSC",
    link: "https://azergold.az/en/",
    color: "#fcaf17",
  },
];

export const testimonials: Testimonial[] = [
  {
    stars: 5,
    comment:
      "CREAT COMPANY ilə əməkdaşlıq zamanı tələb olunan xidmətlər vaxtında və keyfiyyətlə təmin edildi; peşəkarlıq və etibarlılığı yüksək qiymətləndirirəm.",
    name: "Eltibar Abbasov",
    role: "Təmiz Şəhər ASC İdarə Heyətinin sədri",
    image: "07.webp",
  },
  {
    stars: 5,
    comment:
      "Tovuzda aparılan işlər müqavilə şərtlərinə uyğun, vaxtından əvvəl və yüksək keyfiyyətlə yerinə yetirildi; əməkdaşlıqdan məmnun qaldıq.",
    name: "Rəşad Zeynalov",
    role: "Başçının birinci müavini, Tovuz Rayon İcra Hakimiyyəti",
    image: "02.webp",
  },
  {
    stars: 5,
    comment:
      "Tender prosedurlarında Dövlət Satınalmaları qanununa uyğun fəal iştirak etdi; fəaliyyətini məqbul hesab edir və əməkdaşlığı tövsiyə edirik.",
    name: "Kamran Əliyev",
    role: "Baş prokuror (FHN Tikintidə Təhlükəsizliyə Nəzarət Dövlət Agentliyi)",
    image: "06.webp",
  },
  {
    stars: 5,
    comment:
      "Mədəniyyət idarəsinin ehtiyacları vaxtında təmin olundu; CREAT COMPANY-nin xidməti tələbə uyğun və etibarlıdır.",
    name: "Mehdiyev Nurəddin",
    role: "Qazax-Tovuz Regional Mədəniyyət İdarəsinin rəisi",
    image: "05.webp",
  },
  {
    stars: 5,
    comment:
      "Mr. Elnur Mammadov demonstrated exceptional professionalism and adaptability; integral to successful multilingual SAP2000/Lira calculations and shop drawings coordination.",
    name: "Ali Mammadov",
    role: "Technical Director, Eleven-Shanghai LLC (COP29 OC)",
    image: "01.webp",
  },
  {
    stars: 5,
    comment:
      "Creat Company consistently delivered high-quality, responsive and reliable engineering services since Sept 2023; a valuable and recommended partner.",
    name: "Michel Forget",
    role: "Senior Project Manager, ILF Consulting Engineers",
    image: "04.webp",
  },
];
