export const BASE_URI: string =
  "https://pub-5c15a84b97fc4cc889a06969fb95be5f.r2.dev";
export const partners: partners[] = [
  {
    id: 83,
    logo: BASE_URI + "/home/partners/1/logo.png",
    name: "The Conference of the Parties 29",
    link: "https://cop29.az/en",
    animated: true,
    color: "#006a72",
    searchTerm: "COP 29",
  },
  {
    id: 87,
    logo: BASE_URI + "/home/partners/2/logo.png",
    name: "Lightsource BP",
    link: "https://lightsourcebp.com/",
    color: "#009900",
    searchTerm: "Lightsource BP",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/3/logo.png",
    name: "ILF Consulting Engineers",
    link: "https://www.ilf.com/",
    color: "#2f5291",
    searchTerm: "",
  },
  {
    id: 121,
    logo: BASE_URI + "/home/partners/4/logo.png",
    name: "Suez SA",
    link: "https://www.suez.com/en",
    color: "#7ecb23",
    searchTerm: "Suez",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/5/logo.png",
    name: "PMD Projects LLC",
    link: "https://pmdprojects.az/",
    color: "#015ba9",
    searchTerm: "",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/6/logo.png",
    name: "Daşkəsən Dəmir Filiz MMC",
    link: "https://ddf.az",
    color: "#7c5541",
    searchTerm: "",
  },
  {
    id: 133,
    name: "BALXURMA MMC",
    logo: BASE_URI + "/home/partners/7/logo.png",
    link: "https://balkhoorma.com/en",
    color: "#558551",
    animated: true,
    searchTerm: "BALKHOORMA",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/8/logo.png",
    name: "Encotec Company",
    color: "#01205a",
    link: "https://www.encotec.az/",
    searchTerm: "encotec",
  },
  {
    id: 131,
    logo: BASE_URI + "/home/partners/9/logo.png",
    name: "AzerBlast MMC",
    link: "https://azerblast.az/",
    color: "#e96453",
    searchTerm: "AzerBlast",
  },
  {
    id: 152,
    logo: BASE_URI + "/home/partners/10/logo.png",
    name: "Ekologiya və Təbii Sərvətlər Nazirliyi",
    link: "https://eco.gov.az/",
    animated: true,
    color: "#fef212",
    searchTerm: "Ekologiya və Təbii Sərvətlər Nazirliyi",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/11/logo.png",
    name: "İqtisadiyyat Nazirliyi",
    link: "https://www.economy.gov.az/",
    animated: true,
    color: "#a2925e",
    searchTerm: "economy",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/12/logo.png",
    name: "Meliorasiya və Su Təsərrüfatı ASC",
    link: "https://mst.gov.az/",
    animated: true,
    color: "#0191cf",
    searchTerm: "mst",
  },
  {
    id: 154,
    logo: BASE_URI + "/home/partners/13/logo.png",
    name: "Qarabağ – Tarixi və Mədəniyyət Abidələrinin Təmiri və Bərpası",
    animated: true,
    link: "https://rebuildkarabakh.az",
    color: "#000000",
    searchTerm: "Qarabağ",
  },
  {
    id: 134,
    logo: BASE_URI + "/home/partners/14/logo.png",
    name: "Technol MMC",
    link: "https://technol.az/en/",
    color: "#c82327",
    searchTerm: "Technol",
  },
  {
    id: 128,
    logo: BASE_URI + "/home/partners/15/logo.png",
    name: "Sobsan",
    color: "#e12917",
    link: "https://sobsan.com/",
    searchTerm: "Sobsan",
  },
  {
    id: 86,
    logo: BASE_URI + "/home/partners/16/logo.png",
    name: "ACWA Power",
    link: "https://www.acwapower.com/en/",
    color: "#bb332f",
    searchTerm: "ACWA Power",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/17/logo.png",
    name: "Tractabel",
    link: "https://tractebel-engie.com/en",
    color: "#09aafe",
    searchTerm: "tractabel",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/18/logo.png",
    name: "SOCAR Midstream Operations",
    link: "https://www.socarmidstream.az/",
    color: "#e4002b",
    searchTerm: "socar",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/19/logo.png",
    name: "Suraxanı Oil",
    link: "https://www.surakhani-oil.com/",
    color: "#f16333",
    searchTerm: "suraxani",
  },
  {
    id: 85,
    logo: BASE_URI + "/home/partners/20/logo.png",
    name: "Power Construction Corporation of China",
    color: "#c80b4b",
    link: "https://en.powerchina.cn/",
    animated: true,
    searchTerm: "HDEC (PowerChina)",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/21/logo.png",
    name: "MAQRO Group",
    link: "https://www.maqro.ge/",
    color: "#42a13e",
    searchTerm: "maqro",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/22/logo.png",
    name: "Referans Klinik Laboratoriya Mərkəzi",
    color: "#0aa4c7",
    link: "https://referansclc.com/",
    animated: true,
    searchTerm: "referans",
  },
  {
    id: 148,
    logo: BASE_URI + "/home/partners/23/logo.png",
    name: "Qida Təhlıkəsizlik Agentliyi",
    link: "https://afsa.gov.az/",
    animated: true,
    color: "#d9a183",
    searchTerm: "Qida Təhlükəsizlik Agentliyi",
  },
  {
    id: 138,
    logo: BASE_URI + "/home/partners/24/logo.png",
    name: "Azərbaycan Hava Yolları",
    link: "https://azal.az/en/",
    color: "#56bfe7",
    searchTerm: "Azərbaycan Hava Yolları",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/25/logo.png",
    name: "YPT Yılmaz Proses Teknolojileri",
    link: "https://www.ypt.com.tr/",
    color: "#fbb900",
    searchTerm: "ypt",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/26/logo.png",
    name: "CQA International LTD",
    color: "#7aa02f",
    link: "https://www.cqainternational.co.uk/",
    searchTerm: "cqa",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/27/logo.png",
    name: "Bravo Supermarket",
    link: "https://www.bravosupermarket.az/",
    color: "#77bc1f",
    searchTerm: "bravo",
  },
  {
    id: 0,
    logo: BASE_URI + "/home/partners/28/logo.png",
    name: "Azerbaijan Company for Poultry Development",
    color: "#00495b",
    link: "https://az.linkedin.com/company/azerbaijan-company-for-poultry-development",
    animated: true,
    searchTerm: "acpd",
  },
  {
    id: 111,
    logo: BASE_URI + "/home/partners/29/logo.png",
    name: "AzerGold QSC",
    link: "https://azergold.az/en/",
    color: "#fcaf17",
    searchTerm: "Azergold",
  },
];

export const testimonials: Testimonial[] = [
  {
    stars: 5,
    comment:
      "CREAT COMPANY ilə əməkdaşlıq zamanı tələb olunan xidmətlər vaxtında və keyfiyyətlə təmin edildi; peşəkarlıq və etibarlılığı yüksək qiymətləndirirəm.",
    name: "Eltibar Abbasov",
    role: "Təmiz Şəhər ASC İdarə Heyətinin sədri",
    image: "07.webp",
  },
  {
    stars: 5,
    comment:
      "Tovuzda aparılan işlər müqavilə şərtlərinə uyğun, vaxtından əvvəl və yüksək keyfiyyətlə yerinə yetirildi; əməkdaşlıqdan məmnun qaldıq.",
    name: "Rəşad Zeynalov",
    role: "Başçının birinci müavini, Tovuz Rayon İcra Hakimiyyəti",
    image: "02.webp",
  },
  {
    stars: 5,
    comment:
      "Tender prosedurlarında Dövlət Satınalmaları qanununa uyğun fəal iştirak etdi; fəaliyyətini məqbul hesab edir və əməkdaşlığı tövsiyə edirik.",
    name: "Kamran Əliyev",
    role: "FHN Tikintidə Təhlükəsizliyə Nəzarət Dövlət Agentliyi Rəisi",
    image: "06.webp",
  },
  {
    stars: 5,
    comment:
      "Mədəniyyət idarəsinin ehtiyacları vaxtında təmin olundu; CREAT COMPANY-nin xidməti tələbə uyğun və etibarlıdır.",
    name: "Mehdiyev Nurəddin",
    role: "Qazax-Tovuz Regional Mədəniyyət İdarəsinin rəisi",
    image: "05.webp",
  },
  {
    stars: 5,
    comment:
      "Mr. Elnur Mammadov demonstrated exceptional professionalism and adaptability; integral to successful multilingual SAP2000/Lira calculations and shop drawings coordination.",
    name: "Ali Mammadov",
    role: "Technical Director, Eleven-Shanghai LLC (COP29 OC)",
    image: "01.webp",
  },
  {
    stars: 5,
    comment:
      "Creat Company consistently delivered high-quality, responsive and reliable engineering services since Sept 2023; a valuable and recommended partner.",
    name: "Michel Forget",
    role: "Senior Project Manager, ILF Consulting Engineers",
    image: "04.webp",
  },
];
